### ISSUE TITLE
Sound 82 is referenced by Object 234 (Geode Deposite), but it doesn't exist

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/AnotherPlanetData#9] opened 2024-05-16 22:13 UTC
This is causing the client to crash on exit, which I will fix (the client shouldn't crash when a sound doesn't exist).

However, something happened in the workflow to cause this.

The Editor is never supposed to delete a sound that is in use....

**Comment by DopiePanda** [comment] 2024-05-16 23:09
I see that this was caused by missing uploads of sounds after changing setup of my development environment (which relies on copy/pasting to the local folder for the remote repo) due to the issues with the "Please update" screen not allowing me to continue any development after pushing a new update through the AhapUpdateGate without a complete re-install of the game in a completely separate location.

Even fully deleting all game files and un-installing and re-installing in the same folder does not fix the issue regarding the "Please Update" screen. If the client update is live now with the extended logging with regards to this, I can send a copy of the log file post upcoming update Saturday, which also includes the missing sound files.

**Comment by jasonrohrer** [comment] 2024-05-16 23:44
Yes, that client update is live with additional logging

**Comment by DopiePanda** [comment] 2024-11-17 00:54
This was fixed in commit #10

**Closed by DopiePanda** 2024-11-17 00:54 UTC
